import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sarabun } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import { LanguageProvider } from "./context/LanguageContext";


const inter = Inter({ subsets: ["latin"] });

const sarabun = Sarabun({
  variable: "--font-sarabun",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sarabun.className}`}>
        <Providers>
          <LanguageProvider>{children}</LanguageProvider>
        </Providers>

      </body>
    </html>
  );
}
